export const meta = {
  NAME: 'Office of Student Development Services',
  SHORT_NAME: 'SDS',
  LOGO: '/sds_icon.png',
  DESCRIPTION: 'AR & FS Generator',
  SEPARATOR: '|',
} as const;

export const logo = {
  PHILIPPINE_LOGO: '/bagong_pilipinas_logo.png',
  CVSU_LOGO: '/cvsu_logo.png',
  SDS_LOGO: '/sds_icon.png',
};

export const paths = {
  SIGN_IN: '/auth/sign-in',
  SIGN_OUT: '/auth/sign-out',
  ADMIN: '/admin',
  REPORT: '/report',
  ORGANIZATION: '/organization',
  ORGANIZATIONS: '/organizations',
  ORGANIZATION_REPORTS: '/reports',
  ORGANIZATION_EDIT: '/edit',
  LOGS: '/logs',
  ANNOUNCEMENTS: '/announcements',
  EDIT_ANNOUNCEMENTS: '/edit',
  APPOINTMENTS: '/appointments',
  MEMBERS: '/members',
  CBL: '/cbl',
  ORGANIZATION_CREATE: '/create',
  REPORT_CREATE: '/create',
  AUTH_LOGS: '/auth/logs',
  MY_ORGANIZATION: '/my-organization',
  POSITIONS: '/positions',
  SEMESTER: '/semester',

  GENERATED_AR: '/generated-ar',
  FINANCIAL_STATEMENT: '/financial-statement',

  MODIFY_FINANCIAL_STATEMENT: '/modify',
  INFLOWS: '/inflows',
  ADD_INFLOW: '/add-inflow',
  OUTFLOW: '/outflow',
  ADD_OUTFLOW: '/add-outflow',
  MONTHLY: '/monthly',
  SEM_CASH_FLOW: '/semester-cash-flow',
  SEM_SIGNATORIES: '/semester-signatories',
  MONTH_LABEL: '/month-label',
  MONTH_SIGNATORIES: '/month-signatories',
  MONTH_NOTES: '/month-notes',
  MONTH_CASH_FLOW: '/month-cash-flow',
  RECEIPTS: '/receipts',
  EXPENSE_SUMMARY: '/expense-summary',
  FORMS: '/forms',
  LIQUIDATION: '/liquidation',
  INFLOW_COLLECTION: '/inflow-collection',
  INFLOW_IGP: '/inflow-igp',
  SAVE: '/save',
  ADD_NEW_MONTH: '/add-month',

  CREATE: '/create',
  EDIT: '/edit',
  PRINT: '/print',
} as const;
